src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $excerpt;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $meta_description;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $meta_keywords;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text")
     */
    private $tagline;

    /**
     * @ORM\Column(type="text")
     */
    private $composition;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getExcerpt(): ?string
    {
        return $this->excerpt;
    }

    public function setExcerpt(string $excerpt): self
    {
        $this->excerpt = $excerpt;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getMetaDescription(): ?string
    {
        return $this->meta_description;
    }

    public function setMetaDescription(?string $meta_description): self
    {
        $this->meta_description = $meta_description;

        return $this;
    }

    public function getMetaKeywords(): ?string
    {
        return $this->meta_keywords;
    }

    public function setMetaKeywords(?string $meta_keywords): self
    {
        $this->meta_keywords = $meta_keywords;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getTagline(): ?string
    {
        return $this->tagline;
    }

    public function setTagline(string $tagline): self
    {
        $this->tagline = $tagline;

        return $this;
    }

    public function getComposition(): ?string
    {
        return $this->composition;
    }

    public function setComposition(string $composition): self
    {
        $this->composition = $composition;

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('excerpt')
            ->add('body')
            ->add('tagline')
            ->add('composition')
            ->add('image')
            ->add('meta_description')
            ->add('meta_keywords')
            ->add('created_at')
            ->add('updated_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/post")
 */
class PostController extends AbstractController
{
    /**
     * @Route("/", name="post_index", methods={"GET"})
     */
    public function index(PostRepository $postRepository): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('post/index.html.twig', [
            'posts' => $postRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="post_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('post_index');
        }

        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="post_show", methods={"GET"})
     */
    public function show(Post $post): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->render('post/show.html.twig', [
            'post' => $post,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="post_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Post $post): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('post_index');
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="post_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Post $post): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('post_index');
    }
}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/post/_form.html.twig
<script
        src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="//cdn.ckeditor.com/4.12.1/full/ckeditor.js"></script>


{{ form_start(form) }}
<div class="alert alert-danger" role="alert">
    {{ form_errors(form) }}
</div>

<div class="form-group">
    {{ form_label(form.title) }}
    {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.excerpt) }}
    {{ form_widget(form.excerpt, {'attr': {'class': 'form-control', 'id': 'excerpt'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.body) }}
    {{ form_widget(form.body, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.tagline) }}
    {{ form_widget(form.tagline, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.composition) }}
    {{ form_widget(form.composition, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.image) }}
    {{ form_widget(form.image, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.meta_description) }}
    {{ form_widget(form.meta_description, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group">
    {{ form_label(form.meta_keywords) }}
    {{ form_widget(form.meta_keywords, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group" style="display: none;">
    {{ form_label(form.created_at) }}
    {{ form_widget(form.created_at, {'attr': {'class': 'form-control'}}) }}
</div>

<div class="form-group" style="display: none;">
    {{ form_label(form.updated_at) }}
    {{ form_widget(form.updated_at, {'attr': {'class': 'form-control'}}) }}
</div>

<button class="btn btn-success">{{ button_label|default('Save') }}</button>

{{ form_end(form) }}

<script type="text/javascript">
    CKEDITOR.replace('post_excerpt');
    CKEDITOR.replace('post_body');
    CKEDITOR.replace('post_tagline');
    CKEDITOR.replace('post_composition');
</script>

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8">
                <h1>Edit Post</h1>

                {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}
                {{ include('post/_delete_form.html.twig') }}

                <a class="mt-5" href="{{ path('post_index') }}">back to list</a>

            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}

    <style>
        .e-table {
            max-height: 140px;
            overflow: auto;
        }
    </style>

    <div class="container-fluid mt-5">
        <div class="row">
            <div class="col-md-1"></div>
            <div style="background: #fafafa;" class="col-md-10">

                <div class="mt-3 mb-3 float-md-right">
                    <a class="btn btn-sm btn-outline-info" href="/logout">Logout</a>
                </div>

                <h1>Post index</h1>

                <table class="table">
                    <thead>
                    <tr>
                        <th scope="col">Id</th>
                        <th scope="col">Title</th>
                        <th scope="col">Excerpt</th>
                        <th scope="col">Created_at</th>
                        <th scope="col">Updated_at</th>
                        <th style="min-width: 140px;">actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for post in posts %}
                        <tr>
                            <th scope="row">{{ post.id }}</th>
                            <td>
                                <div class="e-table">{{ post.title }}</div>
                            </td>
                            <td class="e-table">
                                <div class="e-table">{{ post.excerpt|raw }}</div>
                            </td>
                            <td class="e-table">
                                <div class="e-table">{{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</div>
                            </td>
                            <td class="e-table">
                                <div class="e-table">{{ post.updatedAt ? post.updatedAt|date('Y-m-d H:i:s') : '' }}</div>
                            </td>
                            <td>
                                <div>
                                    <a class="btn btn-sm btn-outline-info"
                                       href="{{ path('post_show', {'id': post.id}) }}">show</a>
                                    <a class="btn btn-sm btn-outline-success"
                                       href="{{ path('post_edit', {'id': post.id}) }}">edit</a></div>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="10">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                {#                <div class="mt-5">#}
                {#                    <a href="{{ path('post_new') }}">Create new</a>#}
                {#                </div>#}


            </div>
            <div class="col-md-1"></div>
        </div>
    </div>

{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Post{% endblock %}

{% block body %}
    <h1>Create new Post</h1>

    {{ include('post/_form.html.twig') }}

    <a href="{{ path('post_index') }}">back to list</a>
{% endblock %}

templates/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Post</h1>

                <table class="table">
                    <tbody>
                    <tr>
                        <th>Id</th>
                        <td>{{ post.id }}</td>
                    </tr>
                    <tr>
                        <th>Title</th>
                        <td>{{ post.title }}</td>
                    </tr>
                    <tr>
                        <th>Excerpt</th>
                        <td>{{ post.excerpt|raw}}</td>
                    </tr>
                    <tr>
                        <th>Body</th>
                        <td>{{ post.body|raw }}</td>
                    </tr>
                    <tr>
                        <th>Tagline</th>
                        <td>{{ post.tagline|raw }}</td>
                    </tr>
                    <tr>
                        <th>Composition</th>
                        <td>{{ post.composition|raw }}</td>
                    </tr>
                    <tr>
                        <th>Image</th>
                        <td>{{ post.image }}</td>
                    </tr>
                    <tr>
                        <th>Meta_description</th>
                        <td>{{ post.metaDescription }}</td>
                    </tr>
                    <tr>
                        <th>Meta_keywords</th>
                        <td>{{ post.metaKeywords }}</td>
                    </tr>
                    <tr>
                        <th>Created_at</th>
                        <td>{{ post.createdAt ? post.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    <tr>
                        <th>Updated_at</th>
                        <td>{{ post.updatedAt ? post.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                    </tr>
                    </tbody>
                </table>

                <a href="{{ path('post_index') }}">back to list</a>

                <a href="{{ path('post_edit', {'id': post.id}) }}">edit</a>

            </div>
        </div>
    </div>
{% endblock %}